version: '3.8'
services:
  db:
    image: postgres:15-alpine
    container_name: db_dragonball
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: dragonball_api
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: